config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  get 'user/index'
  get 'user/dashboard'
  get 'questionaire', to: 'pages#questionaire', as: 'questionaire'
  get 'user/show'
  get 'user/clubdashboard'
  devise_for :users
  root to: 'pages#home'
  post '/answer', to: 'pages#results', as: 'results'

  resources :clubs do
    resources :offers, except: [:show]
    resources :memberships, only: [:new, :create, :destroy, :update, :edit, :index]
    resources :reviews, only: [:new, :create, :delete]
    resources :rooms, only: [:new, :create] do
      resources :messages, only: [:index, :new, :create]
    end
  end

  Rails.application.routes.draw do
  # [...]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sports, only: [ :index ]
      get "/sports/:query", to: 'sports#search', as: 'api_search'
      post "/messages/new", to: 'messages#create', as: 'api_message_create'
      get "/messages/:room_id/:club_id", to: 'messages#show', as: 'api_message_show'
    end
  end
end

  resources :interests, except: [:show, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card-horizontal.html.erb
<div class="card-origin card-horizontal">
  <div>
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="skateboard" class="avatar-bordered">
  </div>
  <div>
    <h3>Thomas Muller</h3>
    <h4>Amsterdam - Football & Tennis</h4>
    <p>Recently moved from Frankfurt and looking to find a new club</p>
  </div>
</div>

app/views/shared/_card-vertical.html.erb
<div class="card-origin card-vertical my-2 text-center">
  <div>
    <img src="https://pilgrimageyogaonline-yaronguez.netdna-ssl.com/wp-content/uploads/2018/11/Img1-1024x675.jpg" alt="yoga studio" class="card-vertical-cover">
  </div>
  <div>
    <img src="https://d2fdpghjkacqa1.cloudfront.net/wp-content/uploads/2015/06/Semperviva_Events_KundaliniBasics_Gloria_PreviewImage-1.jpg" alt="avatar" class="avatar-bordered-card">
  </div>
  <div class="card-bottom">
    <div class="card-info">
      <h3>Thomas Muller</h3>
      <p>Age: 39, City: Amsterdam</p>
    </div>
    <div class="card-tags">
      <div class="row">
        <div class="col-4">
          <div class="tag">Underwater Hockey</div>
        </div>
        <div class="col-4">
          <div class="tag">Hockey</div>
        </div>
        <div class="col-4">
          <div class="tag">Yoga</div>
        </div>
        <div class="col-4">
          <div class="tag">Football</div>
        </div>
        <div class="col-4">
          <div class="tag">Tennis</div>
        </div>
        <div class="col-4">
          <div class="tag">Bouldering</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_chatroom.html.erb
<div class="chatmodal-outside disabled">
  <div class="chatmodal-inside">
    <div class="<%= "messageBox#{room.id}" %> chatboxes">
      <p class="clubID" style="display: none;"><%= club.id %></p>
      <p class="userID" style="display: none;"><%= current_user.id %></p>
      <p class="roomID" style="display: none;"><%= room.id %></p>
      <p class="authToken" style="display: none;"><%= form_authenticity_token %></p>
    </div>
    <div class="inputBox">
      <label for=<%= "input#{room.id}" %>></label>
      <input type="text" name=<%= "input#{room.id}" %> class=<%= "chatInput#{room.id}" %>>
      <button class="<%= "btn btn-confirm chatButton#{room.id}" %>">Send message</button>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "cz-navbarlogo.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? && current_user.club == nil%>
        <li class="nav-item active">
          <%= link_to "Find Clubs", clubs_path , class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Find Sports", questionaire_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "#{current_user.photo}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Dashboard", user_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% elsif user_signed_in? && current_user.club != nil %>
        <li class="nav-item active">
          <%= link_to "Find Members", user_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Find Clubs", clubs_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Find Sports", questionaire_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "#{current_user.photo}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Club Dashboard", user_clubdashboard_path, class: "dropdown-item" %>
            <%= link_to "My Dashboard", user_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>