config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  get 'user/index'
  get 'user/dashboard'
  get 'questionaire', to: 'pages#questionaire', as: 'questionaire'
  get 'user/show'
  get 'user/clubdashboard'
  devise_for :users
  root to: 'pages#home'
  post '/answer', to: 'pages#results', as: 'results'

  resources :clubs do
    resources :offers, except: [:show]
    resources :memberships, only: [:new, :create, :destroy, :update, :edit, :index]
    resources :reviews, only: [:new, :create, :delete]
    resources :rooms, only: [:new, :create] do
      resources :messages, only: [:index, :new, :create]
    end
  end

  Rails.application.routes.draw do
  # [...]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sports, only: [ :index ]
      get "/sports/:query", to: 'sports#search', as: 'api_search'
      post "/messages/new", to: 'messages#create', as: 'api_message_create'
      get "/messages/:room_id/:club_id", to: 'messages#show', as: 'api_message_show'
    end
  end
end

  resources :interests, except: [:show, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

  has_one :club, foreign_key: 'admin_id'

  has_many :memberships, dependent: :destroy

  has_many :interests, dependent: :destroy
  has_many :sports, through: :interests

  has_many :memberships, dependent: :destroy
  has_many :reviews

  has_many :rooms

  has_many :scores

  validates :name, presence: true
  validates :age, presence: true, inclusion: { in: 14..120, message: "%{value} is not a valid age" }
  validates :address, presence: true
  validates :description, length: { maximum: 500 }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_age,
    against: [ :name, :age],
    associated_against: {
      sports: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    if params[:query] && params[:query] != ""
      @users = User.search_by_name_and_age("#{params[:query]}")
    else
      @users = User.all
    end
  end

  def dashboard
  end

  def show
    @user = User.find(params[:format])
  end

  def clubdashboard
  end
end

app/views/user/clubdashboard.html.erb
<div class="container" style="max-width: 800px;">
  <% @user = current_user %>
  <% @club = @user.club %>

  <div class="section text-center">
    <%= cl_image_tag @club.photo, class: "avatar-bordered-profile my-3" %>
    <h1><%= @club.name %> Dashboard</h1>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <h3 class="text-center">Edit your club</h3>
     <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
      <%= simple_form_for [@club] do |c| %>
      <%= c.input :name %>
      <%= c.input :address %>
      <%= c.input :description %>
      <%= c.input :photo %>
      <%= c.input :photo_cache, as: :hidden %>
      <div class="text-center">
        <%= c.submit "Edit your Club details", class: 'btn btn-confirm'%>
      </div>
      <% end %>
    </div>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <div class="text-center">
      <h3>Offered Sports</h3>
    </div>
    <div class="d-flex justify-content-center">
      <ul style="padding-inline-start:0px; list-style-type: none; width:400px;">
        <% @club.offers.each do |offer| %>
        <li class="my-4 d-flex justify-content-between align-items-center"> <%= offer.sport.name  %> <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, club_offer_path(@club, offer), method: :delete, class: "btn btn-confirm-trash" %>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="form-inputs, form-wrapper" style="width: 400px; margin: 0 auto">
      <%= simple_form_for [@club, Offer.new] do |f| %>
        <%= f.association :sport %>
        <div class="text-center">
          <%= f.submit 'Add Sport', class: 'btn btn-confirm' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="section my-3 card-origin card-dashboard">
     <h3>Membership-Requests</h3>
     <% @club.memberships.each do |membership| %>
     <% if membership.status == "Pending" %>
     <div class="d-flex align-items-center">
        <p><%= membership.user.name %></p>
        <p><%= membership.user.email %></p>
        <p><strong><%= membership.status %></strong></p>
        <%= simple_form_for [@club, membership] do |f| %>
        <%= f.hidden_field :status, value: "Member" %>
        <%= button_tag type: 'submit', class: "btn btn-confirm-trash" do %>
          <i class="fas fa-check"></i>
        <% end %>
        <% end %>
      </div>
    <% end %>
    <% end %>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <h3>Member List</h3>
    <% @club.memberships.each do |membership| %>
    <% if membership.status != "Pending" %>
    <div class="d-flex align-items-center">
      <p><%= membership.user.name %></p>
      <p><%= membership.user.email %></p>
      <p><strong><%= membership.status %></strong></p>
      <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, club_membership_path(@club, membership), method: :delete, class: "btn btn-confirm-trash"   %>
    </div>
    <% end %>
    <% end %>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <h3>This is what members say about <%= @club.name %></h3>
    <% ratings = [] %>
    <% @club.reviews.each do |ra| %>
    <% ratings << ra.rating.to_i %>
    <% end %>
    <% if ratings.size != 0 %>
    <% rating = ratings.sum / ratings.size unless ratings.size == 0 %>
    <% rating.times do  %>
    <span><i class="fas fa-star"></i></span>
    <% end %>
    <% end %>
    <h3><%= pluralize @club.reviews.size, "review" %></h3>
    <div>
      <% if @club.reviews.blank? %>
      <p>Your club has not yet been reviewed...</p>
      <% else %>
      <% @club.reviews.each do |review| %>
      <div class="d-flex align-items-center">
        <p><strong>Name:</strong> <%= review.user.name %></p>
        <p><strong>Comment:</strong><%= review.comment %></p>
        <p><strong>Rating:</strong>
          <% review.rating.times do  %>
          <span><i class="fas fa-star"></i></span>
          <% end %>
        </p>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <h3>Chats of <%= @club.name %></h3>
    <% @club.rooms.each do |chat| %>
    <% user = User.find(chat.user_id) %>
    <p><%= user.name %></p>
    <span><%= link_to "See Chat", club_room_messages_path(@club, chat), class: "btn btn-confirm" %></span>
      <%= render 'shared/chatroom', room: chat, club: @club %>
    <% end %>
  </div>
</div>

<div class="text-center">
  <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalLoginForm">Launch
    Modal Login Form</a>
</div>

app/views/user/dashboard.html.erb
<div class="container" style="max-width: 800px;">
  <div class="section text-center">
    <%= image_tag "#{current_user.photo}", class: "avatar-bordered-profile my-3" %>
    <h1>Hello, <%= current_user.name %> </h1>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <h3 class="text-center">Edit your sports</h3>
    <p class="text-center">These sports will help clubs looking for new members to find you.</p>

    <div class="d-flex justify-content-center">
      <ul style="padding-inline-start:0px; list-style-type: none; width:400px;">
        <% current_user.interests.each do |interest| %>

          <li class="my-4 d-flex justify-content-between align-items-center"> <%= interest.sport.name  %> <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, interest_path(interest), method: :delete, class: "btn btn-confirm-trash" %>
          </li>

        <% end %>
      </ul>
    </div>

    <div class="form-inputs, form-wrapper" style="width: 400px; margin: 0 auto">
      <%= simple_form_for [Interest.new] do |f| %>
        <%= f.association :sport %>
        <div class="text-center">
          <%= f.submit 'Add Sport', class: 'btn btn-confirm' %>
        </div>
      <% end %>
    </div>

  </div>


  <div class="section my-3 card-origin card-dashboard">
    <h3 class="text-center">Memberships</h3>
    <p class="text-center">Your club memberships and requests will appear below</p>

    <div class="row d-flex justify-content-around">
      <% current_user.memberships.each do |membership| %>
          <div class="card-origin card-dashboard m-3 card-vertical text-center">
            <%= link_to club_path(membership.club), class: "card-link" do %>
            <div>
              <img src="<%= membership.club.photo %>" class="avatar-bordered">
            </div>
            <div>
              <h3> <%= membership.club.name %> </h3>
              <% membership.club.sports.each do |sport| %>
              <p> <%= sport.name %></p>
              <% end %>
              <p>Status: <strong><%= membership.status %></strong></p>
            </div>
            <% end %>
          </div>
      <!-- Delete Method missing here -->
      <% end %>
    </div>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <h3 class="text-center">Chats with clubs</h3>
    <% current_user.rooms.each do |chat| %>
    <% @club = Club.find(chat.club_id) %>

    <div class="row d-flex justify-content-around card-origin card-dashboard m-3">
      <img src="<%= @club.photo %>" class="avatar-bordered">
      <p class="btn btn-confirm mb-4" id=<%= "modalButton#{chat.id}" %>>Pop-up chat</p>
    </div>

    <% end %>
  </div>

  <div class="section my-3 card-origin card-dashboard">
    <h3 class="text-center">Change your profile data</h3>


    <%= simple_form_for(current_user, as: current_user, url: registration_path(current_user), html: { method: :put }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs, form-wrapper" style="width: 400px; margin: 0 auto">
          <%= f.input :age, required: true %>
          <%= f.input :address, required: true %>
          <%= f.input :description, required: true %>
          <%= f.input :photo, required: true %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.input :current_password,
            hint: "We need your current password to confirm your changes",
            required: true,
            input_html: { autocomplete: "current-password" } %>
        </div>

        <div class="form-actions text-center">
          <%= f.button :submit, "Update", class: "btn btn-confirm" %>
        </div>
      <% end %>

      <div class="text-center">
        <%= link_to "Change password", edit_user_registration_path, class: "btn btn-confirm" %>
      </div>
  </div>

</div>

<% current_user.rooms.each do |chat| %>
  <%= render 'shared/chatroom', room: chat, club: @club %>
<% end %>

<script>
    const clearMessages = (index) => {
      chatboxes[index].messages = chatboxes[index].html.querySelectorAll('.message');
      chatboxes[index].messages.forEach((message) => {
        chatboxes[index].html.removeChild(message);
      })
    };

    const add_messages_to_box = (data, index) => {
      chatboxes[index].new_messages = data;
      chatboxes[index].new_messages.forEach((msg) => {
        if (msg['sender=']) {
          chatboxes[index].html.insertAdjacentHTML('beforeend', `
            <div class="d-flex justify-content-end message">
              <div class="chat-cloud-club">
                <p><strong>${msg['club_name=']}</strong></p>
                <p>${msg['content=']}</p>
              </div>
            </div>
          `);
        } else {
          chatboxes[index].html.insertAdjacentHTML('beforeend', `
            <div class="chat-cloud-user message">
              <p><strong>${msg['user_name=']}</strong></p>
              <p>${msg['content=']}</p>
            </div>
          `);
        };
      })
      chatboxes[index].html.scrollTop = chatboxes[index].html.scrollHeight;
    };

    const get_new_messages = async () => {
      chatboxes.forEach(async (box, index) => {
        const url = window.location.origin + "/api/v1/messages/" + box.roomId + `/${box.clubId}`;
        await fetch(url)
          .then(response => response.json())
          .then((data) => {
            if (box.new_messages != data) {
              clearMessages(index);
              add_messages_to_box(data, index);
            };
          });
      });
    };

    const send_new_message = async () => {
      chatboxes.forEach((box) => {
        if (box.chatInput.value.trim() != "") {
          const form = document.createElement('form');
          form.method = 'post';
          form.action = '/api/v1/messages/new';

          const hiddenField = document.createElement('input');
          hiddenField.type = 'hidden';
          hiddenField.name = 'authenticity_token';
          hiddenField.value = box.authToken;
          form.appendChild(hiddenField);

          const useridelement = document.createElement('input');
          useridelement.type = 'hidden';
          useridelement.name = 'user_id';
          useridelement.value = box.userId;
          form.appendChild(useridelement);

          const roomIdElement = document.createElement('input');
          roomIdElement.type = 'hidden';
          roomIdElement.name = 'room_id';
          roomIdElement.value = box.roomId;
          form.appendChild(roomIdElement);

          const clubIdElement = document.createElement('input');
          clubIdElement.type = 'hidden';
          clubIdElement.name = 'club_id';
          clubIdElement.value = box.clubId;
          form.appendChild(clubIdElement);

          const chatContent = document.createElement('input');
          chatContent.type = 'hidden';
          chatContent.name = 'content';
          chatContent.value = box.chatInput.value;
          form.appendChild(chatContent);

          document.body.appendChild(form);
          form.submit();
          box.chatInput.value = "";
        }
      })
    setTimeout(function() {
      get_new_messages();
    }, 250);
    };

    const generate_objects = () => {
      const rawChatboxes = document.querySelectorAll('.chatboxes')
      const temp_array = [];
      rawChatboxes.forEach((chatbox) => {
        const temp_obj = new Object;
        temp_obj.html = chatbox;
        temp_obj.messages = chatbox.querySelectorAll('.message');
        temp_obj.clubId = chatbox.querySelector('.clubID').innerText;
        temp_obj.userId = chatbox.querySelector('.userID').innerText;
        temp_obj.roomId = chatbox.querySelector('.roomID').innerText;
        temp_obj.authToken = chatbox.querySelector('.authToken').innerText;
        temp_obj.chatButton = document.getElementsByClassName(`chatButton${temp_obj.roomId}`)[0];
        temp_obj.chatInput = document.getElementsByClassName(`chatInput${temp_obj.roomId}`)[0];
        temp_obj.new_messages = null;
        temp_array.push(temp_obj)
      })
      setInterval(get_new_messages, 5000);
      return temp_array;
    };

    const chatboxes = generate_objects();

    const run_the_thing = () => {
      make_modal_work();
      document.addEventListener('DOMContentLoaded', (event) => {
        get_new_messages();
        chatboxes.forEach((box) => {
          box.chatButton.addEventListener('click', send_new_message);
          box.chatInput.addEventListener('keyup', (event) => {
            if (event.keyCode === 13) {
              send_new_message();
            };
          });
        });
      });
    };

    const make_modal_work = () => {
      chatboxes.forEach((box) => {
        box.modalButton = document.getElementById(`modalButton${box.roomId}`)
        box.modalOutside = box.html.parentNode.parentNode
        box.modalButton.addEventListener('click', (event) => {
          if (event.target === box.modalButton) {
            box.modalOutside.classList.toggle('disabled');
          }
        })
        box.modalOutside.addEventListener('click', (event) => {
          if (event.target === box.modalOutside) {
            box.modalOutside.classList.toggle('disabled');
          }
        })
      })
    }

    run_the_thing();
</script>

app/views/user/index.html.erb
<div class="container">
  <div class="section">
    <h2 style="text-align: center">Find members</h2>
  </div>

  <div class="section">
  <%= simple_form_for user_index_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
      params[:query],
      class: "form-control string required", id: "search_query",
        placeholder: "Find Members"
        %>
        <button name="button" type="submit" class="btn btn-confirm" id="club-s-btn">
          <i class="fas fa-search"></i> Search
        </button>
    </div>
  <% end %>
  </div>

  <div class="section">
  <div class="vertical-card-wrapper row">
    <% @users.each do |user| %>
    <div class="col-sm-12 col-md-6 col-lg-4">
      <div class="card-origin card-vertical my-2 text-center mx-auto">
        <%= link_to user_show_path(user), class:"card-link" do %>
        <div>
          <img src="https://pilgrimageyogaonline-yaronguez.netdna-ssl.com/wp-content/uploads/2018/11/Img1-1024x675.jpg" alt="yoga studio" class="card-vertical-cover">
        </div>
        <div class="avatar-new-position">
          <%= cl_image_tag user.photo, class: "avatar-bordered-card" %>
        </div>
        <div class="card-bottom">
          <div class="card-info">
            <h3 class="club-card-name"><%= user.name %></h3>
            <p>City: Amsterdam</p>
          </div>
          <div class="card-tags">
            <div class="row d-flex">
              <% user.interests.each do |interest| %>
              <div class="col-4">
                <div class="tag"><%= interest.sport.name %></div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
      <% end %>
  </div>
  </div>

</div>

app/views/user/show.html.erb
<div class="container">

  <h1><%= @user.name %></h1>

  <div class="horizontal-card-wrapper row justify-content-center">
    <div class="col-12">
      <div class="card-origin card-horizontal">
        <div>
          <%= cl_image_tag @user.photo, class: "avatar-bordered" %>
        </div>
        <div class="ml-3">
          <h3><%= @user.name %></h3>
          <p><%= @user.address %></p>
          <p><%= @user.description %></p>
          <div>
            <% @user.sports.each do |sport| %>
            <%= sport.name %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row" style="text-align: center">
    <%= link_to "All Members", user_index_path, class:"btn-confirm" %>
  </div>
</div>